name = "gleam_mongo"
target = "erlang"
version = "0.18.1"

description = "A mongodb driver for gleam"
licences = ["Apache-2.0"]
links = [
  {title = "gleam", href = "https://gleam.run"},
  {title = "gleam_bson", href = "https://hexdocs.pm/gleam_bson"},
]
repository = {type = "github", user = "massivefermion", repo = "gleam_mongo"}

internal_modules = [
  "mongo/tcp",
  "mongo/scram",
  "mongo/cursor",
  "mongo/client",
]

[dependencies]
gleam_bitwise = "~> 1.3"
gleam_bson = "~> 0.27"
gleam_crypto = "~> 0.4"
gleam_stdlib = "~> 0.31"

[dev-dependencies]
gleeunit = "~> 0.11"
