name = "mungo"
target = "erlang"
version = "0.27.0"

description = "A MongoDB driver for Gleam (formerly gleam_mongo)"
gleam = ">= 0.32.0"
licences = ["Apache-2.0"]
links = [
  { title = "Gleam", href = "https://gleam.run" },
  { title = "MongoDB", href = "https://www.mongodb.com" },
  { title = "bison", href = "https://hexdocs.pm/bison" },
]
repository = { type = "github", user = "massivefermion", repo = "mungo" }

internal_modules = ["mungo/tcp", "mungo/scram", "mungo/cursor", "mungo/client"]

[dependencies]
bison = "~> 1.7"
gleam_crypto = "~> 1.4"
gleam_erlang = "~> 0.33"
gleam_otp = "~> 0.16"
gleam_stdlib = ">= 0.49.0 or < 2.0.0"
mug = "~> 1.2"
gleam_deque = ">= 1.0.0 and < 2.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.2"
