name = "gleam_mongo"
target = "erlang"
version = "0.16.0"

description = "A mongodb driver for gleam"
licences = ["Apache-2.0"]
links = [
  {title = "gleam", href = "https://gleam.run"},
  {title = "gleam_bson", href = "https://hexdocs.pm/gleam_bson"},
]
repository = {type = "github", user = "massivefermion", repo = "gleam_mongo"}

internal_modules = [
  "tcp",
  "mongo/client",
  "mongo/scram",
]

[dependencies]
gleam_bitwise = "~> 1.2"
gleam_bson = "~> 0.25"
gleam_crypto = "~> 0.3"
gleam_stdlib = "~> 0.28"

[dev-dependencies]
gleeunit = "~> 0.10"
